### ISSUE TITLE
Unable to register with eureka on docker 

### ISSUE THREAD

**Issue by rohitnagesh** [jquatier/eureka-js-client#131]
I have a nodejs applications running on a docker container which I want to register with my eureka instance running on another docker container. Now when I start the containers, using the docker compose, my node-js applications is not getting registered with the eureka server. 

Here is my client configuration on node js application 
```
eureka:
  host: 'eureka-service'
  port: 8761
  servicePath: '/eureka/apps/'
  heartbeatInterval: 30000
  registryFetchInterval: 30000
  fetchRegistry: false
  ssl: false
  useDns: false
  fetchMetadata: false
  preferIpAddress: true
instance:
  app: 'node-service'
  hostName: 'node-service'
  port:
    '$': 8080
    '@enabled': 'true'
  vipAddress: 'node-service'
  dataCenterInfo:
    '@class': 'com.netflix.appinfo.MyDataCenterInfo'
    name: 'MyOwn'
```
and the docker-compose.yml
```
  eureka-service:
    image: rohit/eureka-service:0.0.1
    mem_limit: 1073741824
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://eureka-service:8761"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - 8761:8761
    depends_on:
      config-service:
        condition: service_healthy

  node-service:
    image: rohit/node-service:0.0.1
    mem_limit: 1073741824
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      eureka-service:
        condition: service_healthy
```
My similar configuration for a Java Spring application works.
